[Sariel]
name = "Sariel"
race = "Elf"
cclass = "Ranger"
level = 4
max_hp = 32
cur_hp = 32
ac = 16
initiative_mod = 4
perception = 15
darkvision = true

[Lander]
name = "Lander"
race = "Human"
cclass = "Fighter"
level = 4
max_hp = 36
cur_hp = 36
ac = 17
perception = 14
darkvision = false

[Armek]
name = "Armek"
race = "Dwarf"
cclass = "Cleric"
level = 4
max_hp = 38
cur_hp = 38
ac = 18
perception = 13
darkvision = true

[Pip]
name = "Pip"
race = "Halfling"
cclass = "Rogue"
level = 4
max_hp = 29
cur_hp = 29
ac = 16
perception = 10
darkvision = false

[Dewain]
name = "Dewain"
race = "Elf"
cclass = "Wizard"
level = 4
max_hp = 30
cur_hp = 30
ac = 14
perception = 13
darkvision = true

[Elwing]
name = "Elwing"
race = "Human"
cclass = "Fighter"
level = 4
max_hp = 38
cur_hp = 38
ac = 16
perception = 13
darkvision = false
