name = "Gregorian"
hours_in_day = 24
minutes_in_hour = 60
leap_year_rule = "(year % 4 == 0) and (year % 100 != 0) or (year % 400 == 0)"

default_day = 1
default_month = "January"
default_year = 1970

[months.january]
name = "January"
days = 31

[months.february]
name = "February"
days = 28
leap_year_days = 29

[months.march]
name = "March"
days = 31

[months.april]
name = "April"
days = 30

[months.may]
name = "May"
days = 31

[months.june]
name = "June"
days = 30

[months.july]
name = "July"
days = 31

[months.august]
name = "August"
days = 31

[months.september]
name = "September"
days = 30

[months.october]
name = "October"
days = 31

[months.november]
name = "November"
days = 30

[months.december]
name = "December"
days = 31

[moons.Luna]
name = "Luna"
period = "29.53"